
package com.a20da10.SOAPJava;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Soap", targetNamespace = "http://SOAP.a20da10.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Soap {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.a20da10.soap.EjbInstructorEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "http://SOAP.a20da10.com/", className = "com.a20da10.soap.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://SOAP.a20da10.com/", className = "com.a20da10.soap.GetByIdResponse")
    @Action(input = "http://SOAP.a20da10.com/Soap/getByIdRequest", output = "http://SOAP.a20da10.com/Soap/getByIdResponse")
    public EjbInstructorEntity getById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
