version: '3'
services:
  mysql:
    image: 'mysql:8'
    ports:
    -  '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=school
      - MYSQL_USER=a20da10
      - MYSQL_PASSWORD=secret